In [15]:
#Multivariate Linear Regression using Normal Equation

In [4]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [5]:
from numpy.linalg import inv
data = pd.read_csv('houseprices.csv');
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
x = math.floor(data['bedrooms'].median());
data.bedrooms.fillna(x, inplace=True)
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
max= [data[c].max() for c in data.columns] 
min= [data[c].min() for c in data.columns]
print(max)
print(min)

[4100, 6.0, 30, 810000]
[2600, 3.0, 8, 550000]


In [8]:
#normalize dataset
i=0
for col in data.columns:
    while(i<len(data.columns)):
        data[col] = (data[col]-min[i])/(max[i]-min[i])
        i+=1
        break;
data

area  bedrooms       age     price
0  0.000000  0.000000  0.545455  0.000000
1  0.266667  0.333333  0.318182  0.057692
2  0.400000  0.333333  0.454545  0.230769
3  0.666667  0.000000  1.000000  0.173077
4  0.933333  0.666667  0.000000  0.807692
5  1.000000  1.000000  0.000000  1.000000

In [10]:
#Split dataset to Attribute and Target 
arr =data.values
x_train = []
y = []
a = data.shape
rows = a[0]
cols = a[1]
for i in range(rows):
    x_train.append(arr[i][:-1].tolist())
    y.append(arr[i][-1])
    
print(x_train)
print(y)

[[0.0, 0.0, 0.5454545454545454], [0.26666666666666666, 0.3333333333333333, 0.3181818181818182], [0.4, 0.3333333333333333, 0.45454545454545453], [0.6666666666666666, 0.0, 1.0], [0.9333333333333333, 0.6666666666666666, 0.0], [1.0, 1.0, 0.0]]
[0.0, 0.057692307692307696, 0.23076923076923078, 0.17307692307692307, 0.8076923076923077, 1.0]


In [11]:
m = np.ones((rows,1))
b = np.matrix(x_train)
b = np.concatenate((m,b), axis=1)
b

matrix([[1.        , 0.        , 0.        , 0.54545455],
        [1.        , 0.26666667, 0.33333333, 0.31818182],
        [1.        , 0.4       , 0.33333333, 0.45454545],
        [1.        , 0.66666667, 0.        , 1.        ],
        [1.        , 0.93333333, 0.66666667, 0.        ],
        [1.        , 1.        , 1.        , 0.        ]])

In [12]:
bT=b.T
bT

matrix([[1.        , 1.        , 1.        , 1.        , 1.        ,
         1.        ],
        [0.        , 0.26666667, 0.4       , 0.66666667, 0.93333333,
         1.        ],
        [0.        , 0.33333333, 0.33333333, 0.        , 0.66666667,
         1.        ],
        [0.54545455, 0.31818182, 0.45454545, 1.        , 0.        ,
         0.        ]])

In [13]:
# Coefficient = ((X^T*X)^-1)*X^T*Y
bI = np.linalg.inv(np.matmul(bT,b))
y1 = np.matrix(y)
bT2 = np.matmul(bI, bT)
y1 = y1.T
c = np.matmul(bT2, y1)
c

matrix([[ 0.02691634],
        [ 0.64651409],
        [ 0.26987169],
        [-0.27345305]])

In [14]:
#testing any data
x_test=[[1],]
for j in range (cols-1):
    inp=[float(input("Enter Value:"))]
    x_test.append(inp)
for i in range(cols-1):
    x_test[i+1][0]=(x_test[i+1][0]-min[i])/(max[i]-min[i])
x_test=np.matrix(x_test)
Y1=np.matmul(c.T,x_test)
print(Y1*(max[-1]-min[-1])+min[-1])

Enter Value:3200
Enter Value:4
Enter Value:18
[[615307.4140366]]
